name: Deploy Hexo Blog # Actions 显示的名字，随意设置

on: [push] # 监听到 push 事件后触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout # 拉取当前执行 Actions 仓库的指定分支
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Setup Node # 安装 Node 环境
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"

      - name: Hexo Deploy # 部署步骤，这里以 hexo deploy 为例
        env:
          DEPLOY_BLOG: ${{ secrets.DEPLOY_BLOG }}
        run: |
          git config --global user.name "xyh-study"
          git config --global user.email "2773604834@qq.com"
          npm i -g hexo-cli
          npm install
          hexo g
          hexo d
